# Generated by Django 5.2.4 on 2025-07-18 18:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(unique=True)),
                ('usage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(unique=True)),
                ('weight', models.IntegerField(default=1)),
                ('add_date', models.DateTimeField(default=datetime.datetime(2025, 7, 18, 18, 22, 5, 979241, tzinfo=datetime.timezone.utc))),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.sources')),
            ],
        ),
    ]
