# Generated by Django 5.2.4 on 2025-07-18 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 18, 22, 9, 705902, tzinfo=datetime.timezone.utc)),
        ),
    ]
